spring.application.name=ofertaEv
server.port=8088

Eureka Client

eureka.client.service-url.defaultZone=https://eureka-server-pmc5.onrender.com/eureka
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

eureka.instance.prefer-ip-address=true


subasta.service.url=${SUBASTA_SERVICE_URL:http://localhost:8087/api/v1/subastas}

#postgresql://neondb_owner:npg_16UFapIHWqMj@ep-solitary-pond-apxxbhmn-pooler.c-7.us-east-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require

spring.datasource.url=jdbc:postgresql://ep-solitary-pond-apxxbhmn-pooler.c-7.us-east-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require
spring.datasource.username=neondb_owner
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect